import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Footer from '../components/Footer'
import { useSession} from "next-auth/react";

import Masthehad from '../components/masthead'
import Navbar from '../components/Navbar'


const Home: NextPage = () => {

  const {data:session} = useSession()

  return (
    <div>
      <Head>
        <title>Dekhanee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Dekhanee-Favicon.png" />
      </Head>
      
      <Navbar />
      
      <About />
      <Footer />
 
    </div>
  )
}

export default Home
