import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'

import Masthehad from '../components/masthead'
import Navbar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dekhanee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Dekhanee-Favicon.png" />
      </Head>
      <Navbar />
      <About />
  
      
      <div className="h-96 bg-black"></div>
      <div className="h-96 bg-black"></div>
      <div className="h-96 bg-black"></div>
      <div className="h-96 bg-black"></div>
    </div>
  )
}

export default Home
