import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Footer from '../components/Footer'

import Masthehad from '../components/masthead'
import Navbar from '../components/Navbar'
import Product_categories from '../components/Product_categories'
import Product_list from '../components/Earrings'
import Testimonial from '../components/Testimonial'
import Earrings from '../components/Earrings'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dekhanee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Dekhanee-Favicon.png" />
      </Head>
      <Navbar />
      <About />
      <Product_categories />
     
      <Testimonial />
      <Footer />
 
    </div>
  )
}

export default Home
