import Head from 'next/head'
//import Featured from '../components/Featured'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Slideshow from '../components/Slideshow'
import Image from 'next/image'



export default function Home() {
  return (
    <>
      <Head>
        <title>Dekhanee: The Beautiful</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Dekhanee-Favicon.png" />
      </Head>
      <div className='navbar'>
        <Navbar />
      </div>
      <section className='slideshow'>
        <Slideshow />
      </section>

      <div className='bg-[#131414]'>
        <section id="" className="w-full h-full lg:min-h-screen">
          <div className="flex flex-col gap-5 items-center justify-topcenter font-sans text-[#031926] h-full lg:min-h-screen mx-auto w-full p-2 md:w-1/2">
            <h1 data-aos="fade-up" className="text-5xl md:text-4.4xl mb-5 text-ted-red serif text-white text-center py-6">Certified Reviews</h1>
          </div>

          <section id="productcat" className="w-full h-full lg:min-h-screen">
            <div className="p-6">
              <p className='text-5xl md:text-4.4xl mb-5 text-ted-red serif text-white text-center py-6'>Product Categories</p>
              {/*
              <div className='grid grid-cols-3 gap-10 mx-28 justify-items-center'>
                <button className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white duration-300 ">
                  <Image src="/ear-rings/1.jpeg" width="300" height="350" />
                </button>
                <button className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white duration-300 ">
                  <Image src="/ear-rings/1.jpeg" width="300" height="350" />
                </button>
                <button className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white duration-300 ">
                  <Image src="/ear-rings/1.jpeg" width="300" height="350" />
                </button>
                <button className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white duration-300 ">
                  <Image src="/ear-rings/1.jpeg" width="300" height="350" />
                </button>
                <button className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white duration-300 ">
                  <Image src="/ear-rings/1.jpeg" width="300" height="350" />
                </button>
                <button className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-white duration-300 ">
                  <Image src="/ear-rings/1.jpeg" width="300" height="350" />
                </button>
              </div>*/}
              <section className="text-gray-400 bg-gray-900 body-font">
                <div className="container px-5 py-24 mx-auto">
                  <div className="flex flex-wrap -m-4">
                    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
                      <a className="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" className="object-cover object-center w-full h-full block" src="/ear-rings/1.jpeg" />
                      </a>
                      <div className="mt-4">
                        <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 className="text-white title-font text-lg font-medium">The Catalyzer</h2>
                        <p className="mt-1">$16.00</p>
                      </div>
                    </div>
                    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
                      <a className="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" className="object-cover object-center w-full h-full block" src="/ear-rings/1.jpeg" />
                      </a>
                      <div className="mt-4">
                        <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 className="text-white title-font text-lg font-medium">Shooting Stars</h2>
                        <p className="mt-1">$21.15</p>
                      </div>
                    </div>
                    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
                      <a className="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" className="object-cover object-center w-full h-full block" src="/ear-rings/1.jpeg" />
                      </a>
                      <div className="mt-4">
                        <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 className="text-white title-font text-lg font-medium">Neptune</h2>
                        <p className="mt-1">$12.00</p>
                      </div>
                    </div>
                    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
                      <a className="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" className="object-cover object-center w-full h-full block" src="/ear-rings/1.jpeg" />
                      </a>
                      <div className="mt-4">
                        <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 className="text-white title-font text-lg font-medium">The 400 Blows</h2>
                        <p className="mt-1">$18.40</p>
                      </div>
                    </div>
                    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
                      <a className="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" className="object-cover object-center w-full h-full block" src="/ear-rings/1.jpeg" />
                      </a>
                      <div className="mt-4">
                        <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 className="text-white title-font text-lg font-medium">The Catalyzer</h2>
                        <p className="mt-1">$16.00</p>
                      </div>
                    </div>
                    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
                      <a className="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" className="object-cover object-center w-full h-full block" src="/ear-rings/1.jpeg" />
                      </a>
                      <div className="mt-4">
                        <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 className="text-white title-font text-lg font-medium">Shooting Stars</h2>
                        <p className="mt-1">$21.15</p>
                      </div>
                    </div>
                    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
                      <a className="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" className="object-cover object-center w-full h-full block" src="/ear-rings/1.jpeg" />
                      </a>
                      <div className="mt-4">
                        <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 className="text-white title-font text-lg font-medium">Neptune</h2>
                        <p className="mt-1">$12.00</p>
                      </div>
                    </div>
                    <div className="lg:w-1/4 md:w-1/2 p-4 w-full">
                      <a className="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" className="object-cover object-center w-full h-full block" src="/ear-rings/1.jpeg" />
                      </a>
                      <div className="mt-4">
                        <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 className="text-white title-font text-lg font-medium">The 400 Blows</h2>
                        <p className="mt-1">$18.40</p>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>
          </section>

          <section id="highlights" className="w-full h-full lg:min-h-screen">
            <div className="p-6">
              <p className='text-5xl md:text-4.4xl mb-5 text-ted-red serif text-white text-center py-6'>Highlights</p>
            </div>
          </section>

          <section id="faqs" className="w-full h-full lg:min-h-screen">
            <div className="p-6">
              <p className='text-5xl md:text-4.4xl mb-5 text-ted-red serif text-white text-center py-6'>FAQs</p>
            </div>
          </section>


        </section>
      </div>
      <Footer />

    </>
  )
}
