import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/navbar'
import Slideshow from '../components/Slideshow'



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >

        <Navbar />
        <Slideshow />
        <Footer />
      </div>
    </>
  )
}

export default Home
